### ISSUE TITLE
Phần report bị lặp liên tục  " SETUP STEPS BEFORE !!!"

### ISSUE THREAD

**Issue by letrongtanbs** [anhtester/AutomationFrameworkSelenium#1]

**Comment by anhtester** [comment]
Chào bạn !!!

Lí do là vì:
![image](https://user-images.githubusercontent.com/87883620/162364040-65c641c0-b603-4619-9a39-674c5349459e.png)

Nên để khắc phục thì bên ClientTest chẵn hạn. Bạn sửa lại như thế này:

![image](https://user-images.githubusercontent.com/87883620/162364256-b01cf735-694f-4c46-ae27-018123153191.png)

Cảm ơn bạn đã góp ý. An sẽ xem xét fix lại cho ok hơn. Cảm ơn bạn rất nhiều !!

**Comment by anhtester** [comment]
![image](https://user-images.githubusercontent.com/87883620/162376259-0436d626-c1c2-459d-a7a5-a7c9dc0c182d.png)
