### ISSUE TITLE
phân biệt các func có và không có @Step 

### ISSUE THREAD

**Issue by letrongtanbs** [anhtester/AutomationFrameworkSelenium#2]
https://github.com/anhtester/AutomationFrameworkSelenium/blob/43b96041f5bec120126bf46b63b831ab12d7963b/src/main/java/anhtester/com/utils/WebUI.java#L644-L659

function có anotation @Step thì khác gì function không có vậy anh?
Text trong annotation thì viết vào log nào?

**Comment by anhtester** [comment]
Cái @step đó là mục đích để nó hiển thị step đó trong Allure Report á em.
Đúng ra là viết hết cho đầy đủ mà a lười nên chỉ viết vài cái cần hahaha.

Còn khi em muốn ghi text đó vào log luôn thì thêm một dòng Log.info(text...) bên trong hàm đó luôn.
