### ISSUE TITLE
ObjectUtils   bị null khi gọi

### ISSUE THREAD

**Issue by letrongtanbs** [anhtester/AutomationFrameworkSelenium#3]
https://github.com/anhtester/AutomationFrameworkSelenium/blob/0d76d98de9fbf00c4052ed9e17b19e0492590f16/src/test/java/anhtester/com/projects/website/crm/pages/SignIn/SignInPage.java#L28

Em thử tạo 1 class test cho 1 page khác, trong page có gọi ObjectUtils  để lấy text hoặc xpath. Mà ObjectUtils bị null. Không biết thiếu phần gì anh nhỉ.

Hay phải new ObjectUtils(); trước ạ?

**Comment by anhtester** [comment]
Em kiểm tra xem properties đã khởi tạo chưa. Vì getLocator là nó bỏ vào key từ property file á.
