### ISSUE TITLE
Lỗi khi lấy xpath chứa tiếng Việt hoặc mã UTF8

### ISSUE THREAD

**Issue by letrongtanbs** [anhtester/AutomationFrameworkSelenium#5]
https://github.com/anhtester/AutomationFrameworkSelenium/blob/0d76d98de9fbf00c4052ed9e17b19e0492590f16/src/main/java/anhtester/com/helpers/PropertiesHelpers.java#L85

Có thể sau đó cho return đổi thành:
` return new String(keyval.getBytes(StandardCharsets.ISO_8859_1), StandardCharsets.UTF_8);`

**Comment by anhtester** [comment]
Yeah. Okay. Thank you Tân. Anh sẽ update nó lại trong PropertiesHelper và cả hàm riêng luôn. Ở version 1.4 !!
