### ISSUE TITLE
Getting Exception in extent pdf

### ISSUE THREAD

**Issue by MAutomationLab** [anhtester/AutomationFrameworkSelenium#6]
While running testcases if iam using add screenshot method in onfinshtest image not attaching to extent pdf and getting error for the same

**Comment by anhtester** [comment]
Yeah, I took over. Thank you. Let me check again and let you know later.

**Comment by anhtester** [comment]
@MAutomationLab 
Yeah, I took over. Thank you. Let me check again and let you know later.
